// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzuNReLKrZOBlIbpfveDXoz-AB05d6e58',
    appId: '1:707528861411:web:c9794bbad75f9e804207d6',
    messagingSenderId: '707528861411',
    projectId: 'betterhealth-f9c79',
    authDomain: 'betterhealth-f9c79.firebaseapp.com',
    storageBucket: 'betterhealth-f9c79.appspot.com',
    measurementId: 'G-VPDNB3F7QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCucOm3Smn3P9V9qBJgEBl4R37RLUoL774',
    appId: '1:707528861411:android:5b218da6608244214207d6',
    messagingSenderId: '707528861411',
    projectId: 'betterhealth-f9c79',
    storageBucket: 'betterhealth-f9c79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlloSysD_Q9XZnE188NO6eZ9tLgCLws1g',
    appId: '1:707528861411:ios:1d8dfa24e2aa960b4207d6',
    messagingSenderId: '707528861411',
    projectId: 'betterhealth-f9c79',
    storageBucket: 'betterhealth-f9c79.appspot.com',
    iosClientId: '707528861411-c8mf4kt1nnhvgcaetochld6f94egm1hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.betterHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlloSysD_Q9XZnE188NO6eZ9tLgCLws1g',
    appId: '1:707528861411:ios:1d8dfa24e2aa960b4207d6',
    messagingSenderId: '707528861411',
    projectId: 'betterhealth-f9c79',
    storageBucket: 'betterhealth-f9c79.appspot.com',
    iosClientId: '707528861411-c8mf4kt1nnhvgcaetochld6f94egm1hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.betterHealth',
  );
}
